using UnityEditor;

namespace MergeLegion.Editor
{
    /// <summary>CI helper: scenes are generated by code, so a fresh checkout needs them created before play mode tests.</summary>
    public static class CiSetup
    {
        public static void GenerateScenesOnly()
        {
            ProjectSetup.ApplyProjectSettings();
            BalanceImporter.Import();
            SceneGenerator.GenerateScenes();
            EditorApplication.Exit(0);
        }
    }
}
