using UnityEditor;

namespace MergeLegion.Editor
{
    /// <summary>CI helper: scenes are generated by code, so a fresh checkout needs them created before play mode tests.</summary>
    public static class CiSetup
    {
        public static void GenerateScenesOnly()
        {
            ProjectSetup.ApplyProjectSettings();
            BalanceImporter.Import();
            SceneGenerator.GenerateScenes();
            bool ok = System.IO.File.Exists(SceneGenerator.SceneFolder + "/Main.unity");
            if (!ok) UnityEngine.Debug.LogError("[CiSetup] Scene generation produced no scenes.");
            EditorApplication.Exit(ok ? 0 : 1);
        }
    }
}
